### ISSUE TITLE
Add strong notice when open the app

### ISSUE THREAD

**Issue by Evsio0n** [openjmu/OpenJMU#101]
Add a special function  when  user login

**Comment by AlexVincent525** [comment]
This feature has been publish in this repo https://github.com/AlexVincent525/OpenJMU/commit/e21f8136247ab09d18933a6e5ba7188bfbaeac7b , will be PR soon.

**Comment by AlexVincent525** [comment]
Finished in https://github.com/openjmu/OpenJMU/commit/e21f8136247ab09d18933a6e5ba7188bfbaeac7b

**Comment by Evsio0n** [comment]
Adding announcements at splash page

**Comment by Evsio0n** [comment]
Add a dialog with 2 different types. One users can tap dismiss at the splash page,the other users would quit the app due to some kind of special reason.(Like some third-party version should be prohibited.) The splash page shouldn’t  release until the notification message and token is loaded (Mostly JSON like).PS:Dialog notification should be prior than token
