### ISSUE TITLE
查成绩

### ISSUE THREAD

**Issue by Asjun64** [openjmu/OpenJMU#115]
希望可以像以前那样直接发送消息，然后查成绩
（人不在学校，根本没办法查）

**Comment by AlexVincent525** [comment]
根据目前讨论的结果，由于当前服务无文档且无法访问源码，将在之后提供不同的查询成绩方式，具体会在阶段性决策时说明。

**Comment by AlexVincent525** [comment]
已在进程中。

**Comment by AlexVincent525** [comment]
已在 #134 中完成。
