### ISSUE TITLE
老哥 能打个apk粗来吗 跑不起来

### ISSUE THREAD

**Issue by zhangruiyu** [openjmu/OpenJMU#117]
老哥 能打个apk粗来吗 跑不起来

**Comment by Evsio0n** [comment]
自己修改keys.properties相关,用自己私钥打包.

**Comment by zhangruiyu** [comment]
> 自己修改keys.properties相关,用自己私钥打包.

我改debug了 也是跑步起来 ios也是跑步起来额 想看看

**Comment by AlexVincent525** [comment]
如果你不是我们校内的，跑起来也没用，强登录的应用，必须要校内账户。

**Comment by Evsio0n** [comment]
> > 自己修改keys.properties相关,用自己私钥打包.
> 
> 我改debug了 也是跑步起来 ios也是跑步起来额 想看看

iOS需要开发者权限，还有，这个项目即将闭源，感谢关心

**Comment by AlexVincent525** [comment]
且该应用在酷安已上架
