### ISSUE TITLE
Delete unnecessary icons in APPS & more

### ISSUE THREAD

**Issue by Castver** [openjmu/OpenJMU#151]
**Delete unnecessary icons in APPS**
学生课表 - Already a feature in the app.
网上营业厅 & 网费充值 - Open the same page.
易班 - Just disgusting.
旧版集大通 - We don't need it now.

**New feature**
集大教务 & 诚毅教务 - Is that possible to identify user ID and lead to different pages in app? The icon will just show 教务 for this service

**Comment by AlexVincent525** [comment]
After some investigation, the conclusion goes here:
**学生/教师课表** - Cannot hide, cause we serve course schedule in different webview implement, this will be a backup entry in case of something happened.
**网上营业厅/网费充值** - Both of them will be kept in page, cause they actually provides different url, but on mobile devices it will eventually goes to the same url.
**易班** - Will be REMOVED.
**旧版集大通** - Will be replaced by OpenJMU.

About splitting student from 诚毅, a proper way was found and will be implement soon.

**Comment by AlexVincent525** [comment]
Done with tests.
