### ISSUE TITLE
退出后再次登陆点击登录无效

### ISSUE THREAD

**Issue by Evsio0n** [openjmu/OpenJMU#152]
退出后再次登陆点击登录无效

**Comment by AlexVincent525** [comment]
Might duplicate with #150 , specific case will be: After check user license, then retyping password, the login button would failed. And please provide more detail about this issue.

**Comment by AlexVincent525** [comment]
Close due to duplicate with #150 .

**Comment by AlexVincent525** [comment]
Again, fixed by https://github.com/openjmu/OpenJMU/commit/4ee550a979a58e752bbb6a60205cc0af19f1787c .
