### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.

### ISSUE THREAD

**Issue by PuneethReddyHC** [openjmu/OpenJMU#155]
**Compiler message:**
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.12.0/lib/src/platform_scaffold.dart:222:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('/C:/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
     ` final obstruct = navigationBar.fullObstruction == null ||`
                                     ^^^^^^^^^^^^^^^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.12.0/lib/src/platform_scaffold.dart:223:25: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('/C:/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
          navigationBar.fullObstruction;
                        ^^^^^^^^^^^^^^^

**Comment by AlexVincent525** [comment]
@PuneethReddyHC Hi there, idk why you bring this issue to me, cause it seems not related to my code. Could you provide more info?

**Comment by AlexVincent525** [comment]
No effective response was replied from author, issue will be closed in 24 hours.
