### ISSUE TITLE
网址解析

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#162]
![3 0B}U$8~1KPYKSXI0OB7AS](https://user-images.githubusercontent.com/38584538/68918331-a9081200-07a8-11ea-9400-ca01bcd17e2a.jpg)
![8}9FM~PRJ5TRHNE2V)ZHRE3](https://user-images.githubusercontent.com/38584538/68918332-aa393f00-07a8-11ea-84c9-b68cabad56ff.jpg)
OJ的网页链接把）给吃进去了

**Comment by a328661276** [comment]
集美大学教务处进入提示用户名或者密码错误的解决方法：
①：在内网环境下进入i集大平台（http://i.jmu.edu.cn/）
②：进入管理系统下的集大教务（http://id.jmu.edu.cn/amserver/UI/Login?goto=http://jwgls.jmu.edu.cn/Common/WisdomLogin.aspx） 
③：输入集大通行证的账户（学号）与密码（默认身份证前15）与验证码后登录

**Comment by AlexVincent525** [comment]
Close in https://github.com/openjmu/OpenJMU/commit/3ac202086cc07012234baa17e192f3937ae1d365 .
