### ISSUE TITLE
Add a in-app detection for dark mode

### ISSUE THREAD

**Issue by Evsio0n** [openjmu/OpenJMU#165]
Add a in-app detection for dark mode.
It should auto change to dark-mode when tap notification center dark mode menu.
Maybe it is a flutter issue, I don't know.

**Comment by AlexVincent525** [comment]
Current progress is the Flutter Team still investigating about platform brightness change event, so all we can do is wait.

**Comment by AlexVincent525** [comment]
For now, updated media query after life cycle changed seems worked well, so it's done in 286678a .
Feel free to reopen this if there're any related issue with platform dark mode.
