### ISSUE TITLE
Add course time to course page.

### ISSUE THREAD

**Issue by AlexVincent525** [openjmu/OpenJMU#167]
节次时间
第1节8:00-8:45
第2节8:50-9:35
第3节10:05-10:50
第4节10:55-11:40
第5节14:00-14:45
第6节14:50-15:35
第7节15:55-16:40
第8节16:45-17:30
第9节19:00-19:45
第10节19:50-20:35
第11节20:40-21:25

**Comment by Evsio0n** [comment]
@AlexVincent525 LDTM

**Comment by Evsio0n** [comment]
@AlexVincent525 LGTM

**Comment by AlexVincent525** [comment]
Done in d7ef968 .
