### ISSUE TITLE
优化了清除数据时的提示信息。Optimized the hint message of Data cleaning.

### ISSUE THREAD

**Issue by Lanurence666** [openjmu/OpenJMU#181]
原提示信息：清除数据会将您的所有应用信息及设置清除。确定继续吗？
优化后：您的所有应用信息及设置，包括应用通知，将被清除。确定继续吗？

Original: It will clear all of your app caches and settings. Are you sure?
Optimized: All of your app caches and settings, including in-app notifications, will be cleared. Are you sure?

**Comment by AlexVincent525** [comment]
优化后：清除数据会将您的所有应用内容（包括设置、应用消息）清除。确定继续吗？

**Comment by Lanurence666** [comment]
可以。
