### ISSUE TITLE
Some bugs in V1.0.0 beta

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#212]
![S00928-21283272(1)](https://user-images.githubusercontent.com/38584538/94440257-0ac04780-01d4-11eb-9b8d-8f904cdedf1d.png)
![S00928-21284379](https://user-images.githubusercontent.com/38584538/94440275-13188280-01d4-11eb-877c-a52326901021.png)

课程表默认需要清楚数据才可以不刷新显示日期
![S00928-21281268(1)](https://user-images.githubusercontent.com/38584538/94440326-27f51600-01d4-11eb-979a-7ff4c0e0a022.png)

**Comment by AlexV525** [comment]
> 课程表默认需要清楚数据才可以不刷新显示日期

详细说明？
