### ISSUE TITLE
Android端使用个性化字体导致文字被“吃”

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#46]
![C8EDA5CD310B2E555274CF666F244348](https://user-images.githubusercontent.com/38584538/57616537-f1a00200-75b0-11e9-8485-92337b9df82a.png)

**Comment by AlexVincent525** [comment]
Font's issue seems related with flutter text render engine, will investigate soon.

**Comment by AlexVincent525** [comment]
No more info was provided about issue, will close in next week.
