### ISSUE TITLE
首页刷新失败无限转圈 刷新成功冷却时间有点久

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#47]
#双击刷新失败
使用app一段时间后 双击刷新会无限转圈 退出再进恢复正常
![TL$KEV9}}EM }`M G6NR62W](https://user-images.githubusercontent.com/38584538/57620926-bacfe900-75bc-11e9-9795-f115b11fa7b3.jpg)
能否把这个退出再进“重新载入”的过程放在刷新失败后运行

#双击刷新成功
绿勾的冷却时间有点久 改短点

**Comment by AlexVincent525** [comment]
First issue is related to ticket update. Will be enhanced with ticket update method.

Second issue will be enhanced with later commit.

**Comment by AlexVincent525** [comment]
Fixed in #68 .
