### ISSUE TITLE
“该微博已被屏蔽”应该显示 @XXX

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#60]
![22C636E1343E1D0D8BC8D21FCA5899BE](https://user-images.githubusercontent.com/38584538/57835872-16cf8300-77f2-11e9-8250-46d62287d49d.jpg)
![C012D1B2DB42C89B111301A578954B61](https://user-images.githubusercontent.com/38584538/57835892-1e8f2780-77f2-11e9-9743-f0d427e3734e.jpg)

**Comment by AlexVincent525** [comment]
被屏蔽的微博仍能查看。
