### ISSUE TITLE
课程表缓存 方便快速查看

### ISSUE THREAD

**Issue by a328661276** [openjmu/OpenJMU#64]
用户可选择是否显示当前学期课表，并随时选择当前学期或新学期课表数据更新。

**Comment by AlexVincent525** [comment]
Schedule is will be main page in next version.

**Comment by AlexVincent525** [comment]
Reopen this due to unstable network condition, and course schedule is an important feature for student users.

**Comment by AlexVincent525** [comment]
The whole system needs to be redesigned to fit the offline data saving, including databases and user identification. So it's postponed.

**Comment by AlexVincent525** [comment]
Done in cb3c51a .
